<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return [
    '*unknown*' => '*неизвестно*',
    '- no matter -' => '- не важен -',
    '-no matter-' => '- не важно -',
    '--choose--' => '--выберите--',
    '0.4' => '0.4',
    'Id' => 'Id',
    'This section describes Slides Management' => 'В данном разделе представлены средства управления слайдами',
    'Do you really want to remove the slide?' => 'Вы уверены, что хотите удалить слайд?',
    'Directory "{dir}" is not accessible for write! {link}' => 'Директория "{dir}" не доступна для записи! {link}',
    'You must be an authorized user for view this page!' => 'Для просмотра этой страницы Вам необходимо авторизоваться!',
    'Create slide' => 'Добавить слайд',
    'Create slide and close' => 'Добавить слайд и закрыть',
    'Create slide and continue' => 'Добавить слайд и продолжить',
    'Create' => 'Добавление',
    'Access: * Only for authorized users' => 'Доступ: * только для авторизованных пользователей',
    'Title' => 'Заголовок',
    'Bad characters in {attribute} field' => 'Запрещенные символы в поле {attribute}',
    'Requested page was not found!' => 'Запрошенная страница не найдена!',
    'Change settings' => 'Изменить настройки',
    'Image' => 'Изображение',
    'Find slide' => 'Искать слайд',
    'Uploading files catalog (relatively {path})' => 'Каталог для загрузки файлов (относительно {path})',
    'Content' => 'Контент',
    'Maximum size (in bytes)' => 'Максимальный размер (в байтах)',
    'Minimum size (in bytes)' => 'Минимальный размер (в байтах)',
    'Module for creating slides' => 'Модуль для создания слайдов',
    'On moderation' => 'На модерации',
    'Bad request. Please don\'t repeat similar requests anymore!' => 'Неверный запрос. Пожалуйста, больше не повторяйте такие запросы!',
    'Slides' => 'Слайды',
    'List' => 'Список',
    'Slides list' => 'Список слайдов',
    'Slides - create' => 'Слайды - добавление',
    'Slides - show' => 'Слайды - просмотр',
    'Slides - edit' => 'Слайды - редактирование',
    'Slides - management' => 'Слайды - управление',
    'Slide' => 'Слайд',
    'Slide was created!' => 'Слайд добавлен!',
    'Slide was not found!' => 'Слайд не найден!',
    'Slide was updated!' => 'Слайд обновлен!',
    'Link' => 'Ссылка',
    'Published' => 'Опубликовано',
    'Find slides' => 'Поиск слайдов',
    'Full text' => 'Полный текст',
    'Fields with' => 'Поля, отмеченные',
    'Menu items order' => 'Порядок следования в меню',
    'Show slide' => 'Просмотр слайда',
    'View slide' => 'Просмотреть слайд',
    'Public URL' => 'Публичный урл',
    'Accepted extensions (separated by comma)' => 'Разрешенные расширения (перечислите через запятую)',
    'Edit' => 'Редактирование',
    'Edit slide' => 'Редактирование слайда',
    'Save slide and close' => 'Сохранить слайд и закрыть',
    'Save slide and continue' => 'Сохранить слайд и продолжить',
    'Status' => 'Статус',
    'Remove slide' => 'Удалить слайд',
    'Management' => 'Управление',
    'Slides management' => 'Управление слайдами',
    'Targeting slide was not found!' => 'Целевой слайд не найдена!',
    'Draft' => 'Черновик',
    'yes' => 'да',
    'create' => 'добавление',
    'no' => 'нет',
    'are required.' => 'обязательны.',
    'management' => 'управление',
    'read...' => 'читать...',
    'Item order number' => 'Порядковый номер',
    'Slider' => 'Слайдер',
    'Slide was removed!' => 'Слайд удален!',

    'Manage slides' => 'Управление слайдами',
    'Creating slides' => 'Создание слайдов',
    'Editing slides' => 'Редактирование слайдов',
    'Removing slides' => 'Удаление слайдов',
    'Viewing slides' => 'Просмотр слайдов',
    'List of slides' => 'Просмотр списка слайдов',
];
